FROM docker.drift.inera.se/intyg/app-builder-image:11.0.2

ENV GRADLE_USER_HOME /tmp/cache

WORKDIR /usr/app/

COPY . .

RUN gradle --no-daemon dependencies -DinfraVersion=3.19.0.+ -DcommonVersion=3.19.0.+ -Dfile.encoding=UTF-8

RUN rm -rf /usr/app/*