apiVersion: v1
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <!--

        Copyright (C) 2018 Inera AB (http://www.inera.se)

        This file is part of statistik (https://github.com/sklintyg/statistik).

        statistik is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        statistik is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program.  If not, see <http://www.gnu.org/licenses/>.

    -->
    <configuration>
        <!-- logback config for the Openshift Container Platform (OCP). Stream to stdout, use layout and appenders from infra. -->

        <property name="APP_NAME" value="${APP_NAME:-logsender}"/>

        <include resource="logback-ocp-base.xml"/>

        <logger name="org.springframework" level="ERROR"/>
        <logger name="org.apache" level="ERROR"/>

        <root level="WARN">
            <appender-ref ref="CONSOLE"/>
        </root>

    </configuration>
  logsender.properties: |
    #
    # Copyright (C) 2016 Inera AB (http://www.inera.se)
    #
    # This file is part of sklintyg (https://github.com/sklintyg).
    #
    # sklintyg is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.
    #
    # sklintyg is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    # GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
    #
    env.name=webcert
    activemq.broker.url=${broker.amq.tcp.port}\
    ?jms.nonBlockingRedelivery=true\
    &jms.redeliveryPolicy.maximumRedeliveries=5\
    &jms.redeliveryPolicy.maximumRedeliveryDelay=20000\
    &jms.redeliveryPolicy.initialRedeliveryDelay=15000\
    &jms.redeliveryPolicy.useExponentialBackOff=true\
    &jms.redeliveryPolicy.backOffMultiplier=2

    ntjp.base.url=https://qa.esb.ntjp.se:443/vp
    loggtjanst.logicalAddress = SE165565594230-1000

    receiveLogMessageEndpointUri=jms:queue:${env.name}.log.queue
    receiveAggregatedLogMessageEndpointUri=jms:queue:${env.name}.aggregated.log.queue
    receiveAggregatedLogMessageDLQUri=jms:queue:DLQ.${env.name}.aggregated.log.queue
kind: ConfigMap
metadata:
  creationTimestamp: 2019-03-29T14:24:35Z
  name: logsender-config
  namespace: sintyg
  resourceVersion: "70740258"
  selfLink: /api/v1/namespaces/sintyg/configmaps/logsender-config
  uid: 607f888c-522e-11e9-8635-005056a1b955
