apiVersion: v1
data:
  SAKERHETSTJANST_WS_CERTIFICATE_FILE: ${certificate.folder}/test.intygstjanster.sjunet.org.jks
  SAKERHETSTJANST_WS_CERTIFICATE_TYPE: JKS
  SAKERHETSTJANST_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore.jks
  SAKERHETSTJANST_WS_TRUSTSTORE_TYPE: JKS
kind: ConfigMap
metadata:
  name: logsender-demo-configmap-envvar
type: Opaque
