---

- name: Configure connection factory
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <Resource name='jms/ConnectionFactory'"
    insertbefore: "</Context>"
    line: "    <Resource name='jms/ConnectionFactory' auth='Container' type='org.apache.activemq.ActiveMQConnectionFactory' description='JMS Connection Factory' factory='org.apache.activemq.jndi.JNDIReferenceFactory' brokerURL='{{ activemq_broker_url }}' userName='{{ activemq_username }}' password='{{ activemq_password }}' brokerName='ActiveMQBroker' useEmbeddedBroker='false' />"

- name: Configure async connection factory
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <Resource name='jms/AsyncConnectionFactory'"
    insertbefore: "</Context>"
    line: "    <Resource name='jms/AsyncConnectionFactory' auth='Container' type='org.apache.activemq.ActiveMQConnectionFactory' description='JMS Connection Factory' factory='org.apache.activemq.jndi.JNDIReferenceFactory' brokerURL='{{ async_activemq_broker_url }}' userName='{{ activemq_username }}' password='{{ activemq_password }}' brokerName='ActiveMQBroker' useEmbeddedBroker='false' />"

- name: Configure PDL logging queue
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <Resource name='jms/Queue'"
    insertbefore: "</Context>"
    line: "    <Resource name='jms/Queue' auth='Container' type='org.apache.activemq.command.ActiveMQQueue' description='PDL Logging Queue' factory='org.apache.activemq.jndi.JNDIReferenceFactory' physicalName='{{ environment_name }}.webcert.log.queue' />"

- name: Configure PDL aggregated logging queue
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <Resource name='jms/AggregatedLogSenderQueue'"
    insertbefore: "</Context>"
    line: "    <Resource name='jms/AggregatedLogSenderQueue' auth='Container' type='org.apache.activemq.command.ActiveMQQueue' description='PDL Aggregated Logging Queue' factory='org.apache.activemq.jndi.JNDIReferenceFactory' physicalName='{{ environment_name }}.webcert.aggregated.log.queue' />"

- name: Configure PDL aggregated logging dead letter queue (DLQ)
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <Resource name='jms/AggregatedLogSenderDLQ'"
    insertbefore: "</Context>"
    line: "    <Resource name='jms/AggregatedLogSenderDLQ' auth='Container' type='org.apache.activemq.command.ActiveMQQueue' description='PDL Aggregated Logging Dead Letter Queue' factory='org.apache.activemq.jndi.JNDIReferenceFactory' physicalName='DLQ.{{ environment_name }}.webcert.aggregated.log.queue' />"

