apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: logsender
  name: logsender
spec:
  replicas: 1
  selector:
    app: logsender
    deploymentconfig: logsender
  template:
    metadata:
      labels:
        app: logsender
        deploymentconfig: logsender
        environment: test
    spec:
      containers:
      - env:
        - name: APP_JVM_ENV
          value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dcredentials.file=/opt/inera/credentials/credentials.properties -Dlogsender.config.folder=/opt/inera -Dlogsender.config.file=/opt/inera/logsender-konfiguration/logsender.properties -Dlogsender.logback.file=/opt/inera/logsender-konfiguration/logsender-logback.xml
        - name: ACTIVE_SPRING_PROFILES
          value: test

        image: 172.30.1.1:5000/intygstjanster-test/logsender:latest
        imagePullPolicy: Always
        name: logsender
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5005
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
         - mountPath: /opt/inera/logsender-konfiguration
           name: logsender-konfiguration-test
           readOnly: true
         - mountPath: /opt/inera/certifikat
           name: logsender-certifikat-test
           readOnly: true
         - mountPath: /opt/inera/credentials
           name: logsender-credentials-test
           readOnly: true

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
       - configMap:
           defaultMode: 420
           name: logsender-konfiguration-test
         name: logsender-konfiguration-test
       - name: logsender-certifikat-test
         secret:
           defaultMode: 420
           secretName: logsender-certifikat-test
       - name: logsender-credentials-test
         secret:
           defaultMode: 420
           secretName: logsender-credentials-test
  test: false
